---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/api/v1/categories/{category_id}":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    get:
      summary: show category
      responses:
        '200':
          description: successful
  "/api/v1/categories/{category_id}/recipes":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    get:
      summary: list recipes
      responses:
        '200':
          description: successful
  "/api/v1/recipes/{recipe_id}":
    parameters:
    - name: recipe_id
      in: path
      description: recipe_id
      required: true
      schema:
        type: string
    get:
      summary: show recipe
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
